### ISSUE TITLE
Questions on Profiling Tool

### ISSUE THREAD

**Issue by arjunskumar** [ryuei-washida-nsitexe/ORB_SLAM2_gprof#1]
Is gprof a good performance analysis tool?

**Comment by ryuei-washida-nsitexe** [comment]
Yes, I think so. The short analysis time is one of the good advantages of gprof.

**Comment by ryuei-washida-nsitexe** [comment]
@arjunskumar This was my first time. The first target was the ORB-SLAM2.

**Comment by arjunskumar** [comment]
@ryuei-washida-nsitexe Okay Thanks.
